#select variables needed & mutate them
d <- df %>% 
  select(id, matches("Q11_"), matches("Q10"), matches("Q15"),
         matches("Q16"), matches("Q18"), career, gender, 
         matches("Q3"), matches("Q2")) %>%
  mutate_at(vars(Q10_1:Q10_15),
            funs(recode(.,`0` = 0,`1` = 0, .default = 1, .missing = 0))) %>%
  rowwise(id) %>% 
  mutate(n_val_strat = sum(c(Q11_1, Q11_2, Q11_3, Q11_4, Q11_5, Q11_Other)),
         n_challenges = sum(c(Q10_1, Q10_2, Q10_3, Q10_4, Q10_5, Q10_6, 
                              Q10_7, Q10_8, Q10_9, Q10_10, Q10_11, Q10_12, 
                              Q10_13, Q10_14, Q10_15)),
         n_training_needs_gen = sum(c(Q15_1, Q15_2, Q15_3, Q15_4)),
         multidisc = sum(c(Q18_1, Q18_2, Q18_3, Q18_4, Q18_5, Q18_Other))) %>% 
  ungroup() %>%
  mutate(n_training_needs_ind = if_else(Q16 ==  1, 1, 0),
         gender = recode(gender,
                         `female` = 1,
                         `male` = 0,
                         .missing = 0,
                         .default = .0),
         career = recode(career,
                         `1` = "PhD Student",
                         `2` = "Early-Career Researcher (<5 years since PhD)",
                         `3` = "Mid-Career Researcher (5-15 years since PhD)",
                         `4` = "Senior Researcher (>15 years since PhD)",
                         .default = "Mid-Career Researcher (5-15 years since PhD)"),
         n_val_strat = if_else(is.na(n_val_strat), round(mean(n_val_strat, na.rm=T)), n_val_strat),
         n_challenges = if_else(is.na(n_challenges), round(mean(n_challenges, na.rm=T)), n_challenges),
         n_training_needs_gen = if_else(is.na(n_training_needs_gen), round(mean(n_training_needs_gen, na.rm=T)), 
                                        n_training_needs_gen),
         n_training_needs_ind_miss = if_else(is.na(n_training_needs_ind), 1, 0),
         n_training_needs_ind = if_else(is.na(n_training_needs_ind), round(mean(n_training_needs_ind, na.rm=T)), 
                                        n_training_needs_ind),
         discipline = "Discipline: Other",
         discipline = if_else(multidisc == 0, "Discipline: Other", discipline),
         discipline = if_else(multidisc > 1, "Multi-Disciplinary", discipline),
         discipline = if_else(multidisc == 1 & Q18_1 == 1, "Discipline: Communication Science", discipline),
         discipline = if_else(multidisc == 1 & Q18_2 == 1, "Discipline: Economics", discipline),
         discipline = if_else(multidisc == 1 & Q18_3 == 1, "Discipline: Political Science", discipline),
         discipline = if_else(multidisc == 1 & Q18_4 == 1, "Discipline: Psychology", discipline),
         discipline = if_else(multidisc == 1 & Q18_5 == 1, "Discipline: Sociology", discipline),
         discipline = if_else(multidisc == 1 & Q18_Other == 1, "Discipline: Other", discipline),
         stats_softw = if_else(is.na(Q3_1), round(mean(Q3_1, na.rm=T)), Q3_1),
         math_softw = if_else(is.na(Q3_2), round(mean(Q3_2, na.rm=T)), Q3_2),
         netw_softw = if_else(is.na(Q3_3), round(mean(Q3_3, na.rm=T)), Q3_3),
         quali_softw = if_else(is.na(Q3_4), round(mean(Q3_4, na.rm=T)), Q3_4),
         txt_softw = if_else(is.na(Q3_5), round(mean(Q3_5, na.rm=T)), Q3_5),
         txt_platf = if_else(is.na(Q3_6), round(mean(Q3_6, na.rm=T)), Q3_6),
         opensource_platf = if_else(is.na(Q3_7), round(mean(Q3_7, na.rm=T)), Q3_7),
         quali_txt = if_else(is.na(Q2_1), round(mean(Q2_1, na.rm=T)), Q2_1),
         man_txt = if_else(is.na(Q2_2), round(mean(Q2_2, na.rm=T)), Q2_2),
         comp_txt = if_else(is.na(Q2_3), round(mean(Q2_3, na.rm=T)), Q2_3),
         career = if_else(is.na(career), median(career, na.rm=T), career)) %>% 
  select(id, gender, n_val_strat,
         v_check_doc = Q11_1, 
         v_check_findings = Q11_2, 
         v_gold_standard = Q11_3, 
         v_check_rules = Q11_4, 
         v_chech_procedure = Q11_5, 
         v_check_other = Q11_Other,
         n_challenges,
         c_effort = Q10_1, 
         c_funding = Q10_2, 
         c_training = Q10_3, 
         c_instruction_too_high = Q10_4, 
         c_instruction_too_low = Q10_5, 
         c_documentation = Q10_6, 
         c_measurement = Q10_7, 
         c_language = Q10_8, 
         c_comparability = Q10_9, 
         c_validity = Q10_10, 
         c_loss_contact = Q10_11, 
         c_editors_skepticism = Q10_12, 
         c_peers_skepticism = Q10_13, 
         c_own_skepticism = Q10_14, 
         c_not_relevant = Q10_15,
         n_training_needs_gen,
         t_open_tools = Q15_1,
         t_software = Q15_2, 
         t_theory = Q15_3, 
         t_ethics = Q15_4,
         n_training_needs_ind,
         career, discipline, stats_softw,
         math_softw, netw_softw, quali_softw,
         txt_softw, txt_platf, opensource_platf,
         quali_txt, man_txt, comp_txt) %>%
  mutate(career = factor(career,
                         levels = c("PhD Student",
                                    "Early-Career Researcher (<5 years since PhD)",
                                    "Mid-Career Researcher (5-15 years since PhD)",
                                    "Senior Researcher (>15 years since PhD)")))

tmp <- df %>% 
  select(Q10_1l = Q10_1,
         Q10_2l = Q10_2,
         Q10_3l = Q10_3,
         Q10_4l = Q10_4,
         Q10_5l = Q10_5,
         Q10_6l = Q10_6,
         Q10_7l = Q10_7,
         Q10_8l = Q10_8,
         Q10_9l = Q10_9,
         Q10_10l = Q10_10,
         Q10_11l = Q10_11,
         Q10_12l = Q10_12,
         Q10_13l = Q10_13,
         Q10_14l = Q10_14,
         Q10_15l = Q10_15)
  
d <- d %>% 
  add_column(tmp)
remove(df)
                