---
title: 'Analyses'
author: 
output: 
  github_document:
always_allow_html: true
editor_options: 
  chunk_output_type: console
---

```{r "setup", include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      fig.align = "center",
                      fig.path=('../../report/figures/'))
options(scipen = 1, digits = 2)
library(rmarkdown)
```

# Scripts


# Required Packages &amp; Reproducibility
```{r "env", message=FALSE, warning=F}
rm(list=ls())
source(here::here("src/lib/functions.R"))
```

# Pre-Registered Analyses

```{r "data for analyses"}
load(here("data/intermediate/clean_data.RData"))
```


## Pre-Registered Hypotheses 
```{r "h-pre-reg", fig.align="center", fig.height=15, fig.width=14}
source(here("src/analysis/pre-registered.R"))
p

kbl(df, booktabs =T, caption = "Effect of Identifying as Female for Pre-Registered Hypothesis") %>%
  kable_styling(latex_options = c("striped", "hold_position"),
                full_width = F, fixed_thead = T, position = "center") %>%
  column_spec(1, width = "10cm") %>%
  column_spec(2, width = "2cm")  %>%
  column_spec(3, width = "4cm") %>%
  column_spec(4, width = "4cm")
```

## Explorative Results
```{r "explorative", fig.align="center",  fig.height=25, fig.width=20}
source(here("src/analysis/explorative.R"))

(descr + descr_1) / (descr_softw + descr_method) + 
  plot_layout(guides = "collect") & theme(legend.position = "bottom")
  

p_exp1 + p_exp2 + 
  plot_layout(guides = "collect") & theme(legend.position = "bottom")
```

```{r "types-dv", fig.align="center",  fig.height=25, fig.width=20}
source(here("src/analysis/explorative-types.R"))

((pv / pt + plot_layout(guides = 'auto')) | pc) +
  plot_layout(guides = "collect") & theme(legend.position = "bottom")
  
```

# T-test authorship ranking

```{r "ttest", fig.height=6, fig.width=8}
source(here("src/analysis/Review.R"))
r1
```

```{r "challenges-distribution", fig.height=10, fig.width=15}
source(here("src/analysis/challenges.R"))
c1
c2
```